version: '3.8'
services:
  app:
    build: .
    container_name: telegram-bot-local
    ports:
      - "7999:8080"
    env_file:
      - .env
  cache-redis:
    image: redis:7.2.4-alpine
    restart: always
      