kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 'redis'
          ports:
            - containerPort: 6379
