apiVersion: v1
kind: Service
metadata:
  name: telegram-service
  labels:
    app: telegram-express-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: telegram-express-app
